### ISSUE TITLE
iphone 7p 音乐列表日期无法正常显示

### ISSUE THREAD

**Issue by justin-init** [lishuaixingNewBee/gordanTv#2]
iphone 7p 真机音乐列表日期显示的是NaN-aN-aN，模拟器上没问题
![wechatimg21](https://user-images.githubusercontent.com/21174047/40119360-0ccb3d6c-594f-11e8-9d43-0c5c1625ea67.jpeg)

**Comment by lishuaixingNewBee** [comment]
已解决

**Comment by justin-init** [comment]
验证了可以显示
